// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commdef.proto
// Protobuf C++ Version: 7.36.1

#ifndef commdef_2eproto_2epb_2eh
#define commdef_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_commdef_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_commdef_2eproto {
  static const ::uint32_t offsets[];
};
namespace InnerCmd {
enum ProtoId : int;
extern const uint32_t ProtoId_internal_data_[];
}  // namespace InnerCmd
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::InnerCmd::ProtoId_internal_data_>
    internal::EnumTraitsImpl::value<::InnerCmd::ProtoId>;
}  // namespace protobuf
}  // namespace google

namespace InnerCmd {
enum ProtoId : int {
  CS_NULL = 0,
  GG_LS_Login_REQ = 1,
  LS_GG_Login_ACK = 2,
  GG_LS_Logoff_NTF = 3,
  LS_GG_Kickoff_NTF = 4,
  GG_LS_ReportPlayerNum_NTF = 5,
  GG_LS_SetPasswordTemp_REQ = 6,
  LS_GG_SetPasswordTemp_ACK = 7,
  ProtoId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ProtoId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ProtoId_internal_data_[];
inline constexpr ProtoId ProtoId_MIN =
    static_cast<ProtoId>(0);
inline constexpr ProtoId ProtoId_MAX =
    static_cast<ProtoId>(7);
[[nodiscard]] inline bool ProtoId_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int ProtoId_ARRAYSIZE = 7 + 1;
[[nodiscard]] const ::std::string& ProtoId_Name(ProtoId value);
template <typename T>
[[nodiscard]] const ::std::string& ProtoId_Name(T value) {
  static_assert(::std::is_same<T, ProtoId>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ProtoId_Name().");
  return ProtoId_Name(static_cast<ProtoId>(value));
}
[[nodiscard]] bool ProtoId_Parse(
    ::absl::string_view name, ProtoId* PROTOBUF_NONNULL value);
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace InnerCmd


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::InnerCmd::ProtoId> : std::true_type {};
template <>
struct internal::LiteEnumFuncs<::InnerCmd::ProtoId> {
  static constexpr bool kIsDefined = true;
  static constexpr auto kParseFunc = ::InnerCmd::ProtoId_Parse;
  static constexpr auto kNameFunc = ::InnerCmd::ProtoId_Name<int>;
};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // commdef_2eproto_2epb_2eh
