#pragma once

#define CLI_LG_MSG_ID_MIN     1
#define CLI_LG_MSG_ID_MAX     19
#define CLI_GG_MSG_ID_MIN     20
#define CLI_GG_MSG_ID_MAX     200
#define CLI_GS_MSG_ID_MIN     1000
#define CLI_GS_MSG_ID_MAX     2999
#define GG_LG_MSG_ID_MIN      3000
#define GG_LG_MSG_ID_MAX      3099
#define GG_LS_MSG_ID_MIN      3100
#define GG_LS_MSG_ID_MAX      3199
#define GG_DB_MSG_ID_MIN      3200
#define GG_DB_MSG_ID_MAX      3999
#define GG_GS_MSG_ID_MIN      4000
#define GG_GS_MSG_ID_MAX      4999
#define GG_MS_MSG_ID_MIN      5000
#define GG_MS_MSG_ID_MAX      5999
#define GS_DB_MSG_ID_MIN      6000
#define GS_DB_MSG_ID_MAX      7999
#define GS_MS_MSG_ID_MIN      8000
#define GS_MS_MSG_ID_MAX      8999
#define GG_WS_MSG_ID_MIN      9000
#define GG_WS_MSG_ID_MAX      9199
#define GS_WS_MSG_ID_MIN      9200
#define GS_WS_MSG_ID_MAX      9399

#define PROTO_SUCCESS            1
#define PROTO_FAILURE            0
#define HEALTH_TRUE              1
#define HEALTH_FALSE             0
#define LOGIN_MY                 1
#define LOGIN_AP                 2
#define LOGOFF_TYPE_LOGOUT       0
#define LOGOFF_TYPE_RESELROLE    1
#define ROLE_MAX_NUM             4
#define ROLENAME_MAX_LEN         32
#define ACTIVATION_INFO_LEN      1024
#define GIFTCODE_INFO_LEN        1024
#define ROLE_MAX_NUM_ALL         8
#define GUILDNAME_MAX_LEN        31
#define ROLEDATA_LEN             94208
#define MAPCODE_LEN              31
#define PTID_LEN                 64
#define PLAYERID_LEN             21
#define LOGINID_LEN              21
#define ACCOUNT_LEN              33
#define PASSWORD_LEN             33
#define NAME_MAX_LEN             33
#define TIME_STRING_LEN          20
#define ONLINEMSG_LEN            64
#define ORDERID_LEN              64
#define CliGsOldMsgLen           94208
#define URL_MAX_LEN              2046
#define GDCMD_MAX_LEN            4096
#define BENCHMARK_CGS            1
#define BENCHMARK_CS             0
#define BM_DIR_CS                1
#define BM_DIR_SC                0
#define BM_Cli                   0
#define BM_LG                    1
#define BM_LS                    2
#define BM_DB                    3
#define BM_GG                    4
#define BM_MS                    5
#define BM_GS                    6
#define CLIENT_PC                0
#define CLIENT_IOS               1
#define CLIENT_ANDROID           2
#define INVITECODE_LEN           12
#define GDCMDINFO_MAX_LEN        40960
#define FLAG_LEN                 1
#define ONLINEPLAYERIDS_MAX_LEN  1024
#define ONLINEPLAYERINFO_MAX_LEN 8192
#define ZONELIST_MAX_LEN         40960
#define UINT8_MAX_LEN            256
#define MSGDATA_LEN              65535
#define COMMDEFS_MSGID_RANGE 3
#define COMMDEFS_MSGID_OFFSET 19999

