// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commdef.proto
// Protobuf C++ Version: 7.36.1

#ifndef commdef_2eproto_2epb_2eh
#define commdef_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_commdef_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_commdef_2eproto {
  static const ::uint32_t offsets[];
};
namespace InnerCmd {
enum ProtoId : int;
extern const uint32_t ProtoId_internal_data_[];
class SErrCode;
struct SErrCodeGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern SErrCodeGlobalsTypeInternal SErrCode_globals_;
extern const ::google::protobuf::internal::ClassDataLite SErrCode_class_data_;
#else
extern const SErrCodeGlobalsTypeInternal SErrCode_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class SIPAddr;
struct SIPAddrGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern SIPAddrGlobalsTypeInternal SIPAddr_globals_;
extern const ::google::protobuf::internal::ClassDataLite SIPAddr_class_data_;
#else
extern const SIPAddrGlobalsTypeInternal SIPAddr_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace InnerCmd
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::InnerCmd::ProtoId_internal_data_>
    internal::EnumTraitsImpl::value<::InnerCmd::ProtoId>;
}  // namespace protobuf
}  // namespace google

namespace InnerCmd {
enum ProtoId : int {
  CS_NULL = 0,
  GG_LS_Login_REQ = 1,
  LS_GG_Login_ACK = 2,
  GG_LS_Logoff_NTF = 3,
  LS_GG_Kickoff_NTF = 4,
  GG_LS_ReportPlayerNum_NTF = 5,
  GG_LS_SetPasswordTemp_REQ = 6,
  LS_GG_SetPasswordTemp_ACK = 7,
  ProtoId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ProtoId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ProtoId_internal_data_[];
inline constexpr ProtoId ProtoId_MIN =
    static_cast<ProtoId>(0);
inline constexpr ProtoId ProtoId_MAX =
    static_cast<ProtoId>(7);
[[nodiscard]] inline bool ProtoId_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int ProtoId_ARRAYSIZE = 7 + 1;
[[nodiscard]] const ::std::string& ProtoId_Name(ProtoId value);
template <typename T>
[[nodiscard]] const ::std::string& ProtoId_Name(T value) {
  static_assert(::std::is_same<T, ProtoId>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ProtoId_Name().");
  return ProtoId_Name(static_cast<ProtoId>(value));
}
[[nodiscard]] bool ProtoId_Parse(
    ::absl::string_view name, ProtoId* PROTOBUF_NONNULL value);
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED SIPAddr final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:InnerCmd.SIPAddr) */ {
  using Super_ = ::google::protobuf::MessageLite;

 public:
  inline SIPAddr() : SIPAddr(nullptr) {}
  ~SIPAddr() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SIPAddr* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SIPAddr));
  }
#endif

  template <typename = void>
  explicit constexpr SIPAddr(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline SIPAddr(const SIPAddr& from) : SIPAddr(nullptr, from) {}
  inline SIPAddr(SIPAddr&& from) noexcept : SIPAddr(nullptr, ::std::move(from)) {}
  inline SIPAddr& operator=(const SIPAddr& from) {
    CopyFrom(from);
    return *this;
  }
  inline SIPAddr& operator=(SIPAddr&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const SIPAddr& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<SIPAddr>(&SIPAddr_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SIPAddr& a, SIPAddr& b) { a.Swap(&b); }
  inline void Swap(SIPAddr* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SIPAddr* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] SIPAddr* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<SIPAddr>(arena);
  }
  void CopyFrom(const SIPAddr& from);
  void MergeFrom(const SIPAddr& from) { SIPAddr::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SIPAddr* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "InnerCmd.SIPAddr"; }

  explicit SIPAddr(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SIPAddr(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SIPAddr& from);
  SIPAddr(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SIPAddr&& from) noexcept
      : SIPAddr(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIPFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // uint32 IP = 1;
  void clear_ip() ;
  [[nodiscard]] ::uint32_t ip() const;
  void set_ip(::uint32_t value);

  private:
  ::uint32_t _internal_ip() const;
  void _internal_set_ip(::uint32_t value);

  public:
  // uint32 Port = 2;
  void clear_port() ;
  [[nodiscard]] ::uint32_t port() const;
  void set_port(::uint32_t value);

  private:
  ::uint32_t _internal_port() const;
  void _internal_set_port(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:InnerCmd.SIPAddr)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SIPAddr& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t ip_;
    ::uint32_t port_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_commdef_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED SErrCode final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:InnerCmd.SErrCode) */ {
  using Super_ = ::google::protobuf::MessageLite;

 public:
  inline SErrCode() : SErrCode(nullptr) {}
  ~SErrCode() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SErrCode* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SErrCode));
  }
#endif

  template <typename = void>
  explicit constexpr SErrCode(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline SErrCode(const SErrCode& from) : SErrCode(nullptr, from) {}
  inline SErrCode(SErrCode&& from) noexcept : SErrCode(nullptr, ::std::move(from)) {}
  inline SErrCode& operator=(const SErrCode& from) {
    CopyFrom(from);
    return *this;
  }
  inline SErrCode& operator=(SErrCode&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const SErrCode& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<SErrCode>(&SErrCode_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SErrCode& a, SErrCode& b) { a.Swap(&b); }
  inline void Swap(SErrCode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SErrCode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] SErrCode* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<SErrCode>(arena);
  }
  void CopyFrom(const SErrCode& from);
  void MergeFrom(const SErrCode& from) { SErrCode::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SErrCode* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "InnerCmd.SErrCode"; }

  explicit SErrCode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SErrCode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SErrCode& from);
  SErrCode(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SErrCode&& from) noexcept
      : SErrCode(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrCodeFieldNumber = 1,
  };
  // uint32 ErrCode = 1;
  void clear_errcode() ;
  [[nodiscard]] ::uint32_t errcode() const;
  void set_errcode(::uint32_t value);

  private:
  ::uint32_t _internal_errcode() const;
  void _internal_set_errcode(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:InnerCmd.SErrCode)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 1,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SErrCode& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t errcode_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_commdef_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SIPAddr

// uint32 IP = 1;
inline void SIPAddr::clear_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::uint32_t SIPAddr::ip() const {
  // @@protoc_insertion_point(field_get:InnerCmd.SIPAddr.IP)
  return _internal_ip();
}
inline void SIPAddr::set_ip(::uint32_t value) {
  _internal_set_ip(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:InnerCmd.SIPAddr.IP)
}
inline ::uint32_t SIPAddr::_internal_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_;
}
inline void SIPAddr::_internal_set_ip(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_ = value;
}

// uint32 Port = 2;
inline void SIPAddr::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::uint32_t SIPAddr::port() const {
  // @@protoc_insertion_point(field_get:InnerCmd.SIPAddr.Port)
  return _internal_port();
}
inline void SIPAddr::set_port(::uint32_t value) {
  _internal_set_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:InnerCmd.SIPAddr.Port)
}
inline ::uint32_t SIPAddr::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void SIPAddr::_internal_set_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// -------------------------------------------------------------------

// SErrCode

// uint32 ErrCode = 1;
inline void SErrCode::clear_errcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errcode_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::uint32_t SErrCode::errcode() const {
  // @@protoc_insertion_point(field_get:InnerCmd.SErrCode.ErrCode)
  return _internal_errcode();
}
inline void SErrCode::set_errcode(::uint32_t value) {
  _internal_set_errcode(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:InnerCmd.SErrCode.ErrCode)
}
inline ::uint32_t SErrCode::_internal_errcode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errcode_;
}
inline void SErrCode::_internal_set_errcode(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errcode_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace InnerCmd


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::InnerCmd::ProtoId> : std::true_type {};
template <>
struct internal::LiteEnumFuncs<::InnerCmd::ProtoId> {
  static constexpr bool kIsDefined = true;
  static constexpr auto kParseFunc = ::InnerCmd::ProtoId_Parse;
  static constexpr auto kNameFunc = ::InnerCmd::ProtoId_Name<int>;
};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // commdef_2eproto_2epb_2eh
