// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commdef.proto
// Protobuf C++ Version: 7.36.1

#include "commdef.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace InnerCmd {
class SIPAddr::_Internal {
 public:
  using HasBits = decltype(::std::declval<SIPAddr>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SIPAddr, _impl_._has_bits_);
};

constexpr SIPAddr::ParseTableT_ SIPAddr::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SIPAddr, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::InnerCmd::SIPAddr>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // uint32 Port = 2;
      {::_pbi::TcParser::FastV32S1,
       {16, 1, 0,
        PROTOBUF_FIELD_OFFSET(SIPAddr, _impl_.port_)}},
      // uint32 IP = 1;
      {::_pbi::TcParser::FastV32S1,
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(SIPAddr, _impl_.ip_)}},
    }}, {{
      65535, 65535
    }}, {{
      // uint32 IP = 1;
      {PROTOBUF_FIELD_OFFSET(SIPAddr, _impl_.ip_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // uint32 Port = 2;
      {PROTOBUF_FIELD_OFFSET(SIPAddr, _impl_.port_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr SIPAddr::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : ip_{0u},
        port_{0u} {}

template <typename>
constexpr SIPAddr::SIPAddr(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL SIPAddr::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SIPAddr(arena);
}
constexpr auto SIPAddr::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SIPAddr), alignof(SIPAddr));
}
constexpr auto SIPAddr::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SIPAddr::MergeImpl,
          Super_::GetNewImpl<SIPAddr>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SIPAddr::SharedDtor,
          Super_::GetClearImpl<SIPAddr>(), &SIPAddr::ByteSizeLong,
              &SIPAddr::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SIPAddr, _impl_._cached_size_),
          true,
      },
      "InnerCmd.SIPAddr",
  };
}
struct SIPAddrGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SIPAddrGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SIPAddr_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SIPAddr::InternalGenerateClassData_(
            _default, &SIPAddr_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SIPAddr>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SIPAddrGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SIPAddr _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SIPAddr>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SIPAddrGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SIPAddrGlobalsTypeInternal SIPAddr_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SIPAddr_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SIPAddr_globals_.GetClassData();
#else
  return SIPAddr_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SErrCode::_Internal {
 public:
  using HasBits = decltype(::std::declval<SErrCode>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SErrCode, _impl_._has_bits_);
};

constexpr SErrCode::ParseTableT_ SErrCode::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SErrCode, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::InnerCmd::SErrCode>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // uint32 ErrCode = 1;
      {::_pbi::TcParser::FastV32S1,
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(SErrCode, _impl_.errcode_)}},
    }}, {{
      65535, 65535
    }}, {{
      // uint32 ErrCode = 1;
      {PROTOBUF_FIELD_OFFSET(SErrCode, _impl_.errcode_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr SErrCode::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : errcode_{0u} {}

template <typename>
constexpr SErrCode::SErrCode(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL SErrCode::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SErrCode(arena);
}
constexpr auto SErrCode::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SErrCode), alignof(SErrCode));
}
constexpr auto SErrCode::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SErrCode::MergeImpl,
          Super_::GetNewImpl<SErrCode>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SErrCode::SharedDtor,
          Super_::GetClearImpl<SErrCode>(), &SErrCode::ByteSizeLong,
              &SErrCode::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SErrCode, _impl_._cached_size_),
          true,
      },
      "InnerCmd.SErrCode",
  };
}
struct SErrCodeGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SErrCodeGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SErrCode_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SErrCode::InternalGenerateClassData_(
            _default, &SErrCode_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SErrCode>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SErrCodeGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SErrCode _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SErrCode>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SErrCodeGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SErrCodeGlobalsTypeInternal SErrCode_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SErrCode_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SErrCode_globals_.GetClassData();
#else
  return SErrCode_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace InnerCmd
namespace InnerCmd {
PROTOBUF_CONSTINIT const uint32_t ProtoId_internal_data_[] = {
    524288u, 0u, };
static const char ProtoId_names[] = {
    "CS_NULL"
    "GG_LS_Login_REQ"
    "GG_LS_Logoff_NTF"
    "GG_LS_ReportPlayerNum_NTF"
    "GG_LS_SetPasswordTemp_REQ"
    "LS_GG_Kickoff_NTF"
    "LS_GG_Login_ACK"
    "LS_GG_SetPasswordTemp_ACK"
};

static const ::google::protobuf::internal::EnumEntry ProtoId_entries[] = {
    {{&ProtoId_names[0], 7}, 0},
    {{&ProtoId_names[7], 15}, 1},
    {{&ProtoId_names[22], 16}, 3},
    {{&ProtoId_names[38], 25}, 5},
    {{&ProtoId_names[63], 25}, 6},
    {{&ProtoId_names[88], 17}, 4},
    {{&ProtoId_names[105], 15}, 2},
    {{&ProtoId_names[120], 25}, 7},
};

static const int ProtoId_entries_by_number[] = {
    0,  // 0 -> CS_NULL
    1,  // 1 -> GG_LS_Login_REQ
    6,  // 2 -> LS_GG_Login_ACK
    2,  // 3 -> GG_LS_Logoff_NTF
    5,  // 4 -> LS_GG_Kickoff_NTF
    3,  // 5 -> GG_LS_ReportPlayerNum_NTF
    4,  // 6 -> GG_LS_SetPasswordTemp_REQ
    7,  // 7 -> LS_GG_SetPasswordTemp_ACK
};

[[nodiscard]] bool ProtoId_Parse(::absl::string_view name,
                                  ProtoId* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      ProtoId_entries, 8, name, &int_value);
  if (success) {
    *value = static_cast<ProtoId>(int_value);
  }
  return success;
}
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    ProtoId_strings[8] = {};

[[nodiscard]] const ::std::string& ProtoId_Name(ProtoId value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      ProtoId_entries, ProtoId_entries_by_number, 8,
      ProtoId_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(ProtoId_entries,
                                  ProtoId_entries_by_number,
                                  8, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : ProtoId_strings[idx].get();
}
// ===================================================================

SIPAddr::SIPAddr(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SIPAddr_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:InnerCmd.SIPAddr)
}
SIPAddr::SIPAddr(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SIPAddr& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SIPAddr_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SIPAddr::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
     {}

inline void SIPAddr::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, ip_),
           0,
           offsetof(Impl_, port_) -
               offsetof(Impl_, ip_) +
               sizeof(Impl_::port_));
}
SIPAddr::~SIPAddr() {
  // @@protoc_insertion_point(destructor:InnerCmd.SIPAddr)
  SharedDtor(*this);
}
inline void SIPAddr::SharedDtor(MessageLite& self) {
  SIPAddr& this_ = static_cast<SIPAddr&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite SIPAddr_class_data_ =
    SIPAddr::InternalGenerateClassData_(SIPAddr_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SIPAddr::GetClassData() const {
  return SIPAddr_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SIPAddr::GetClassData() const {
  return SIPAddr_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SIPAddr::ParseTableT_
    SIPAddr::_table_ =
        SIPAddr::InternalGenerateParseTable_(SIPAddr_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void SIPAddr::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:InnerCmd.SIPAddr)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&this_._impl_.ip_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.port_) -
                 reinterpret_cast<char*>(&this_._impl_.ip_)) +
                 sizeof(_impl_.port_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SIPAddr::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SIPAddr& this_ = static_cast<const SIPAddr&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SIPAddr::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SIPAddr& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:InnerCmd.SIPAddr)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 IP = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_ip() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_ip(), target);
    }
  }

  // uint32 Port = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_port() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_port(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:InnerCmd.SIPAddr)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SIPAddr::ByteSizeLong(const MessageLite& base) {
  const SIPAddr& this_ = static_cast<const SIPAddr&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SIPAddr::ByteSizeLong() const {
  const SIPAddr& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:InnerCmd.SIPAddr)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // uint32 IP = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_ip() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_ip());
      }
    }
    // uint32 Port = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_port() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_port());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void SIPAddr::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<SIPAddr*>(&to_msg);
  auto& from = static_cast<const SIPAddr&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:InnerCmd.SIPAddr)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_ip() != 0) {
        _this->_impl_.ip_ = from._impl_.ip_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_port() != 0) {
        _this->_impl_.port_ = from._impl_.port_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void SIPAddr::CopyFrom(const SIPAddr& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:InnerCmd.SIPAddr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SIPAddr::InternalSwap(SIPAddr* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SIPAddr, _impl_.port_)
      + sizeof(SIPAddr::_impl_.port_)
      - PROTOBUF_FIELD_OFFSET(SIPAddr, _impl_.ip_)>(
          reinterpret_cast<char*>(&_impl_.ip_),
          reinterpret_cast<char*>(&other->_impl_.ip_));
}

// ===================================================================

SErrCode::SErrCode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SErrCode_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:InnerCmd.SErrCode)
}
SErrCode::SErrCode(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SErrCode& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SErrCode_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SErrCode::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
     {}

inline void SErrCode::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.errcode_ = {};
}
SErrCode::~SErrCode() {
  // @@protoc_insertion_point(destructor:InnerCmd.SErrCode)
  SharedDtor(*this);
}
inline void SErrCode::SharedDtor(MessageLite& self) {
  SErrCode& this_ = static_cast<SErrCode&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite SErrCode_class_data_ =
    SErrCode::InternalGenerateClassData_(SErrCode_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SErrCode::GetClassData() const {
  return SErrCode_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SErrCode::GetClassData() const {
  return SErrCode_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SErrCode::ParseTableT_
    SErrCode::_table_ =
        SErrCode::InternalGenerateParseTable_(SErrCode_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void SErrCode::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:InnerCmd.SErrCode)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  this_._impl_.errcode_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SErrCode::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SErrCode& this_ = static_cast<const SErrCode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SErrCode::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SErrCode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:InnerCmd.SErrCode)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 ErrCode = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_errcode() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_errcode(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:InnerCmd.SErrCode)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SErrCode::ByteSizeLong(const MessageLite& base) {
  const SErrCode& this_ = static_cast<const SErrCode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SErrCode::ByteSizeLong() const {
  const SErrCode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:InnerCmd.SErrCode)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

   {
    // uint32 ErrCode = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_errcode() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_errcode());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void SErrCode::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<SErrCode*>(&to_msg);
  auto& from = static_cast<const SErrCode&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:InnerCmd.SErrCode)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_errcode() != 0) {
      _this->_impl_.errcode_ = from._impl_.errcode_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void SErrCode::CopyFrom(const SErrCode& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:InnerCmd.SErrCode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SErrCode::InternalSwap(SErrCode* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.errcode_, other->_impl_.errcode_);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace InnerCmd
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
