// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gg_ls.proto
// Protobuf C++ Version: 7.36.1

#ifndef gg_5fls_2eproto_2epb_2eh
#define gg_5fls_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "commdef.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_gg_5fls_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_gg_5fls_2eproto {
  static const ::uint32_t offsets[];
};
namespace GG_LS_Cmd {
class PKG_GG_LS_Login_REQ;
struct PKG_GG_LS_Login_REQGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PKG_GG_LS_Login_REQGlobalsTypeInternal PKG_GG_LS_Login_REQ_globals_;
extern const ::google::protobuf::internal::ClassDataLite PKG_GG_LS_Login_REQ_class_data_;
#else
extern const PKG_GG_LS_Login_REQGlobalsTypeInternal PKG_GG_LS_Login_REQ_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class PKG_GG_LS_Logoff_NTF;
struct PKG_GG_LS_Logoff_NTFGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PKG_GG_LS_Logoff_NTFGlobalsTypeInternal PKG_GG_LS_Logoff_NTF_globals_;
extern const ::google::protobuf::internal::ClassDataLite PKG_GG_LS_Logoff_NTF_class_data_;
#else
extern const PKG_GG_LS_Logoff_NTFGlobalsTypeInternal PKG_GG_LS_Logoff_NTF_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class PKG_LS_GG_Kickoff_NTF;
struct PKG_LS_GG_Kickoff_NTFGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PKG_LS_GG_Kickoff_NTFGlobalsTypeInternal PKG_LS_GG_Kickoff_NTF_globals_;
extern const ::google::protobuf::internal::ClassDataLite PKG_LS_GG_Kickoff_NTF_class_data_;
#else
extern const PKG_LS_GG_Kickoff_NTFGlobalsTypeInternal PKG_LS_GG_Kickoff_NTF_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class PKG_LS_GG_Login_ACK;
struct PKG_LS_GG_Login_ACKGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PKG_LS_GG_Login_ACKGlobalsTypeInternal PKG_LS_GG_Login_ACK_globals_;
extern const ::google::protobuf::internal::ClassDataLite PKG_LS_GG_Login_ACK_class_data_;
#else
extern const PKG_LS_GG_Login_ACKGlobalsTypeInternal PKG_LS_GG_Login_ACK_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace GG_LS_Cmd
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace GG_LS_Cmd {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PKG_LS_GG_Login_ACK final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:GG_LS_Cmd.PKG_LS_GG_Login_ACK) */ {
  using Super_ = ::google::protobuf::MessageLite;

 public:
  inline PKG_LS_GG_Login_ACK() : PKG_LS_GG_Login_ACK(nullptr) {}
  ~PKG_LS_GG_Login_ACK() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PKG_LS_GG_Login_ACK* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PKG_LS_GG_Login_ACK));
  }
#endif

  template <typename = void>
  explicit constexpr PKG_LS_GG_Login_ACK(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PKG_LS_GG_Login_ACK(const PKG_LS_GG_Login_ACK& from) : PKG_LS_GG_Login_ACK(nullptr, from) {}
  inline PKG_LS_GG_Login_ACK(PKG_LS_GG_Login_ACK&& from) noexcept : PKG_LS_GG_Login_ACK(nullptr, ::std::move(from)) {}
  inline PKG_LS_GG_Login_ACK& operator=(const PKG_LS_GG_Login_ACK& from) {
    CopyFrom(from);
    return *this;
  }
  inline PKG_LS_GG_Login_ACK& operator=(PKG_LS_GG_Login_ACK&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const PKG_LS_GG_Login_ACK& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PKG_LS_GG_Login_ACK>(&PKG_LS_GG_Login_ACK_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PKG_LS_GG_Login_ACK& a, PKG_LS_GG_Login_ACK& b) { a.Swap(&b); }
  inline void Swap(PKG_LS_GG_Login_ACK* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PKG_LS_GG_Login_ACK* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PKG_LS_GG_Login_ACK* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<PKG_LS_GG_Login_ACK>(arena);
  }
  void CopyFrom(const PKG_LS_GG_Login_ACK& from);
  void MergeFrom(const PKG_LS_GG_Login_ACK& from) { PKG_LS_GG_Login_ACK::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PKG_LS_GG_Login_ACK* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "GG_LS_Cmd.PKG_LS_GG_Login_ACK"; }

  explicit PKG_LS_GG_Login_ACK(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PKG_LS_GG_Login_ACK(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PKG_LS_GG_Login_ACK& from);
  PKG_LS_GG_Login_ACK(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PKG_LS_GG_Login_ACK&& from) noexcept
      : PKG_LS_GG_Login_ACK(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPTIDFieldNumber = 2,
    kAbyDataInfoFieldNumber = 4,
    kResultFieldNumber = 1,
    kWPlatTypeFieldNumber = 3,
    kErrorFieldNumber = 5,
  };
  // string PTID = 2;
  void clear_ptid() ;
  [[nodiscard]] const ::std::string& ptid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ptid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ptid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ptid();
  void set_allocated_ptid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ptid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ptid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ptid();

  public:
  // string abyDataInfo = 4;
  void clear_abydatainfo() ;
  [[nodiscard]] const ::std::string& abydatainfo() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_abydatainfo(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_abydatainfo();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_abydatainfo();
  void set_allocated_abydatainfo(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_abydatainfo() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_abydatainfo(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_abydatainfo();

  public:
  // uint32 Result = 1;
  void clear_result() ;
  [[nodiscard]] ::uint32_t result() const;
  void set_result(::uint32_t value);

  private:
  ::uint32_t _internal_result() const;
  void _internal_set_result(::uint32_t value);

  public:
  // uint32 wPlatType = 3;
  void clear_wplattype() ;
  [[nodiscard]] ::uint32_t wplattype() const;
  void set_wplattype(::uint32_t value);

  private:
  ::uint32_t _internal_wplattype() const;
  void _internal_set_wplattype(::uint32_t value);

  public:
  // uint32 error = 5;
  void clear_error() ;
  [[nodiscard]] ::uint32_t error() const;
  void set_error(::uint32_t value);

  private:
  ::uint32_t _internal_error() const;
  void _internal_set_error(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 5,
                          0, 53,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PKG_LS_GG_Login_ACK& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ptid_;
    ::google::protobuf::internal::ArenaStringPtr abydatainfo_;
    ::uint32_t result_;
    ::uint32_t wplattype_;
    ::uint32_t error_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gg_5fls_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PKG_LS_GG_Kickoff_NTF final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF) */ {
  using Super_ = ::google::protobuf::MessageLite;

 public:
  inline PKG_LS_GG_Kickoff_NTF() : PKG_LS_GG_Kickoff_NTF(nullptr) {}
  ~PKG_LS_GG_Kickoff_NTF() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PKG_LS_GG_Kickoff_NTF* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PKG_LS_GG_Kickoff_NTF));
  }
#endif

  template <typename = void>
  explicit constexpr PKG_LS_GG_Kickoff_NTF(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PKG_LS_GG_Kickoff_NTF(const PKG_LS_GG_Kickoff_NTF& from) : PKG_LS_GG_Kickoff_NTF(nullptr, from) {}
  inline PKG_LS_GG_Kickoff_NTF(PKG_LS_GG_Kickoff_NTF&& from) noexcept : PKG_LS_GG_Kickoff_NTF(nullptr, ::std::move(from)) {}
  inline PKG_LS_GG_Kickoff_NTF& operator=(const PKG_LS_GG_Kickoff_NTF& from) {
    CopyFrom(from);
    return *this;
  }
  inline PKG_LS_GG_Kickoff_NTF& operator=(PKG_LS_GG_Kickoff_NTF&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const PKG_LS_GG_Kickoff_NTF& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PKG_LS_GG_Kickoff_NTF>(&PKG_LS_GG_Kickoff_NTF_globals_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(PKG_LS_GG_Kickoff_NTF& a, PKG_LS_GG_Kickoff_NTF& b) { a.Swap(&b); }
  inline void Swap(PKG_LS_GG_Kickoff_NTF* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PKG_LS_GG_Kickoff_NTF* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PKG_LS_GG_Kickoff_NTF* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<PKG_LS_GG_Kickoff_NTF>(arena);
  }
  void CopyFrom(const PKG_LS_GG_Kickoff_NTF& from);
  void MergeFrom(const PKG_LS_GG_Kickoff_NTF& from) { PKG_LS_GG_Kickoff_NTF::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PKG_LS_GG_Kickoff_NTF* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF"; }

  explicit PKG_LS_GG_Kickoff_NTF(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PKG_LS_GG_Kickoff_NTF(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PKG_LS_GG_Kickoff_NTF& from);
  PKG_LS_GG_Kickoff_NTF(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PKG_LS_GG_Kickoff_NTF&& from) noexcept
      : PKG_LS_GG_Kickoff_NTF(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPTIDFieldNumber = 1,
  };
  // string PTID = 1;
  void clear_ptid() ;
  [[nodiscard]] const ::std::string& ptid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ptid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ptid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ptid();
  void set_allocated_ptid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ptid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ptid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ptid();

  public:
  // @@protoc_insertion_point(class_scope:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 1,
                          0, 44,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PKG_LS_GG_Kickoff_NTF& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ptid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gg_5fls_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PKG_GG_LS_Logoff_NTF final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF) */ {
  using Super_ = ::google::protobuf::MessageLite;

 public:
  inline PKG_GG_LS_Logoff_NTF() : PKG_GG_LS_Logoff_NTF(nullptr) {}
  ~PKG_GG_LS_Logoff_NTF() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PKG_GG_LS_Logoff_NTF* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PKG_GG_LS_Logoff_NTF));
  }
#endif

  template <typename = void>
  explicit constexpr PKG_GG_LS_Logoff_NTF(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PKG_GG_LS_Logoff_NTF(const PKG_GG_LS_Logoff_NTF& from) : PKG_GG_LS_Logoff_NTF(nullptr, from) {}
  inline PKG_GG_LS_Logoff_NTF(PKG_GG_LS_Logoff_NTF&& from) noexcept : PKG_GG_LS_Logoff_NTF(nullptr, ::std::move(from)) {}
  inline PKG_GG_LS_Logoff_NTF& operator=(const PKG_GG_LS_Logoff_NTF& from) {
    CopyFrom(from);
    return *this;
  }
  inline PKG_GG_LS_Logoff_NTF& operator=(PKG_GG_LS_Logoff_NTF&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const PKG_GG_LS_Logoff_NTF& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PKG_GG_LS_Logoff_NTF>(&PKG_GG_LS_Logoff_NTF_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PKG_GG_LS_Logoff_NTF& a, PKG_GG_LS_Logoff_NTF& b) { a.Swap(&b); }
  inline void Swap(PKG_GG_LS_Logoff_NTF* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PKG_GG_LS_Logoff_NTF* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PKG_GG_LS_Logoff_NTF* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<PKG_GG_LS_Logoff_NTF>(arena);
  }
  void CopyFrom(const PKG_GG_LS_Logoff_NTF& from);
  void MergeFrom(const PKG_GG_LS_Logoff_NTF& from) { PKG_GG_LS_Logoff_NTF::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PKG_GG_LS_Logoff_NTF* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "GG_LS_Cmd.PKG_GG_LS_Logoff_NTF"; }

  explicit PKG_GG_LS_Logoff_NTF(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PKG_GG_LS_Logoff_NTF(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PKG_GG_LS_Logoff_NTF& from);
  PKG_GG_LS_Logoff_NTF(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PKG_GG_LS_Logoff_NTF&& from) noexcept
      : PKG_GG_LS_Logoff_NTF(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPTIDFieldNumber = 1,
  };
  // string PTID = 1;
  void clear_ptid() ;
  [[nodiscard]] const ::std::string& ptid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ptid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ptid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ptid();
  void set_allocated_ptid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ptid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ptid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ptid();

  public:
  // @@protoc_insertion_point(class_scope:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 1,
                          0, 43,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PKG_GG_LS_Logoff_NTF& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ptid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gg_5fls_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PKG_GG_LS_Login_REQ final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:GG_LS_Cmd.PKG_GG_LS_Login_REQ) */ {
  using Super_ = ::google::protobuf::MessageLite;

 public:
  inline PKG_GG_LS_Login_REQ() : PKG_GG_LS_Login_REQ(nullptr) {}
  ~PKG_GG_LS_Login_REQ() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PKG_GG_LS_Login_REQ* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PKG_GG_LS_Login_REQ));
  }
#endif

  template <typename = void>
  explicit constexpr PKG_GG_LS_Login_REQ(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PKG_GG_LS_Login_REQ(const PKG_GG_LS_Login_REQ& from) : PKG_GG_LS_Login_REQ(nullptr, from) {}
  inline PKG_GG_LS_Login_REQ(PKG_GG_LS_Login_REQ&& from) noexcept : PKG_GG_LS_Login_REQ(nullptr, ::std::move(from)) {}
  inline PKG_GG_LS_Login_REQ& operator=(const PKG_GG_LS_Login_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline PKG_GG_LS_Login_REQ& operator=(PKG_GG_LS_Login_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const PKG_GG_LS_Login_REQ& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PKG_GG_LS_Login_REQ>(&PKG_GG_LS_Login_REQ_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PKG_GG_LS_Login_REQ& a, PKG_GG_LS_Login_REQ& b) { a.Swap(&b); }
  inline void Swap(PKG_GG_LS_Login_REQ* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PKG_GG_LS_Login_REQ* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PKG_GG_LS_Login_REQ* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<PKG_GG_LS_Login_REQ>(arena);
  }
  void CopyFrom(const PKG_GG_LS_Login_REQ& from);
  void MergeFrom(const PKG_GG_LS_Login_REQ& from) { PKG_GG_LS_Login_REQ::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PKG_GG_LS_Login_REQ* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "GG_LS_Cmd.PKG_GG_LS_Login_REQ"; }

  explicit PKG_GG_LS_Login_REQ(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PKG_GG_LS_Login_REQ(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PKG_GG_LS_Login_REQ& from);
  PKG_GG_LS_Login_REQ(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PKG_GG_LS_Login_REQ&& from) noexcept
      : PKG_GG_LS_Login_REQ(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAuthActFieldNumber = 1,
    kAuthStrFieldNumber = 2,
    kInviteCodeFieldNumber = 8,
    kAPTypeFieldNumber = 3,
    kClientVersionFieldNumber = 4,
    kClientTypeFieldNumber = 5,
    kAreaGroupFieldNumber = 6,
    kIpFieldNumber = 7,
    kReserveFieldNumber = 9,
  };
  // string AuthAct = 1;
  void clear_authact() ;
  [[nodiscard]] const ::std::string& authact() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_authact(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_authact();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_authact();
  void set_allocated_authact(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_authact() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_authact(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_authact();

  public:
  // string AuthStr = 2;
  void clear_authstr() ;
  [[nodiscard]] const ::std::string& authstr() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_authstr(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_authstr();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_authstr();
  void set_allocated_authstr(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_authstr() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_authstr(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_authstr();

  public:
  // string InviteCode = 8;
  void clear_invitecode() ;
  [[nodiscard]] const ::std::string& invitecode() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_invitecode(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_invitecode();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_invitecode();
  void set_allocated_invitecode(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_invitecode() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_invitecode(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_invitecode();

  public:
  // uint32 APType = 3;
  void clear_aptype() ;
  [[nodiscard]] ::uint32_t aptype() const;
  void set_aptype(::uint32_t value);

  private:
  ::uint32_t _internal_aptype() const;
  void _internal_set_aptype(::uint32_t value);

  public:
  // uint32 ClientVersion = 4;
  void clear_clientversion() ;
  [[nodiscard]] ::uint32_t clientversion() const;
  void set_clientversion(::uint32_t value);

  private:
  ::uint32_t _internal_clientversion() const;
  void _internal_set_clientversion(::uint32_t value);

  public:
  // uint32 ClientType = 5;
  void clear_clienttype() ;
  [[nodiscard]] ::uint32_t clienttype() const;
  void set_clienttype(::uint32_t value);

  private:
  ::uint32_t _internal_clienttype() const;
  void _internal_set_clienttype(::uint32_t value);

  public:
  // uint32 AreaGroup = 6;
  void clear_areagroup() ;
  [[nodiscard]] ::uint32_t areagroup() const;
  void set_areagroup(::uint32_t value);

  private:
  ::uint32_t _internal_areagroup() const;
  void _internal_set_areagroup(::uint32_t value);

  public:
  // uint32 Ip = 7;
  void clear_ip() ;
  [[nodiscard]] ::uint32_t ip() const;
  void set_ip(::uint32_t value);

  private:
  ::uint32_t _internal_ip() const;
  void _internal_set_ip(::uint32_t value);

  public:
  // uint32 Reserve = 9;
  void clear_reserve() ;
  [[nodiscard]] ::uint32_t reserve() const;
  void set_reserve(::uint32_t value);

  private:
  ::uint32_t _internal_reserve() const;
  void _internal_set_reserve(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<4, 9,
                          0, 70,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PKG_GG_LS_Login_REQ& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr authact_;
    ::google::protobuf::internal::ArenaStringPtr authstr_;
    ::google::protobuf::internal::ArenaStringPtr invitecode_;
    ::uint32_t aptype_;
    ::uint32_t clientversion_;
    ::uint32_t clienttype_;
    ::uint32_t areagroup_;
    ::uint32_t ip_;
    ::uint32_t reserve_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gg_5fls_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PKG_GG_LS_Login_REQ

// string AuthAct = 1;
inline void PKG_GG_LS_Login_REQ::clear_authact() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authact_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& PKG_GG_LS_Login_REQ::authact() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthAct)
  return _internal_authact();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PKG_GG_LS_Login_REQ::set_authact(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.authact_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthAct)
}
inline ::std::string* PROTOBUF_NONNULL PKG_GG_LS_Login_REQ::mutable_authact()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_authact();
  // @@protoc_insertion_point(field_mutable:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthAct)
  return _s;
}
inline const ::std::string& PKG_GG_LS_Login_REQ::_internal_authact() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.authact_.Get();
}
inline void PKG_GG_LS_Login_REQ::_internal_set_authact(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authact_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PKG_GG_LS_Login_REQ::_internal_mutable_authact() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.authact_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PKG_GG_LS_Login_REQ::release_authact() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthAct)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.authact_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.authact_.Set("", GetArena());
  }
  return released;
}
inline void PKG_GG_LS_Login_REQ::set_allocated_authact(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.authact_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.authact_.IsDefault()) {
    _impl_.authact_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthAct)
}

// string AuthStr = 2;
inline void PKG_GG_LS_Login_REQ::clear_authstr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authstr_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& PKG_GG_LS_Login_REQ::authstr() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthStr)
  return _internal_authstr();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PKG_GG_LS_Login_REQ::set_authstr(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.authstr_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthStr)
}
inline ::std::string* PROTOBUF_NONNULL PKG_GG_LS_Login_REQ::mutable_authstr()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_authstr();
  // @@protoc_insertion_point(field_mutable:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthStr)
  return _s;
}
inline const ::std::string& PKG_GG_LS_Login_REQ::_internal_authstr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.authstr_.Get();
}
inline void PKG_GG_LS_Login_REQ::_internal_set_authstr(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authstr_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PKG_GG_LS_Login_REQ::_internal_mutable_authstr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.authstr_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PKG_GG_LS_Login_REQ::release_authstr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthStr)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.authstr_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.authstr_.Set("", GetArena());
  }
  return released;
}
inline void PKG_GG_LS_Login_REQ::set_allocated_authstr(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.authstr_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.authstr_.IsDefault()) {
    _impl_.authstr_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthStr)
}

// uint32 APType = 3;
inline void PKG_GG_LS_Login_REQ::clear_aptype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aptype_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::uint32_t PKG_GG_LS_Login_REQ::aptype() const {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Login_REQ.APType)
  return _internal_aptype();
}
inline void PKG_GG_LS_Login_REQ::set_aptype(::uint32_t value) {
  _internal_set_aptype(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Login_REQ.APType)
}
inline ::uint32_t PKG_GG_LS_Login_REQ::_internal_aptype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.aptype_;
}
inline void PKG_GG_LS_Login_REQ::_internal_set_aptype(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aptype_ = value;
}

// uint32 ClientVersion = 4;
inline void PKG_GG_LS_Login_REQ::clear_clientversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientversion_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::uint32_t PKG_GG_LS_Login_REQ::clientversion() const {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Login_REQ.ClientVersion)
  return _internal_clientversion();
}
inline void PKG_GG_LS_Login_REQ::set_clientversion(::uint32_t value) {
  _internal_set_clientversion(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Login_REQ.ClientVersion)
}
inline ::uint32_t PKG_GG_LS_Login_REQ::_internal_clientversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clientversion_;
}
inline void PKG_GG_LS_Login_REQ::_internal_set_clientversion(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientversion_ = value;
}

// uint32 ClientType = 5;
inline void PKG_GG_LS_Login_REQ::clear_clienttype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clienttype_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::uint32_t PKG_GG_LS_Login_REQ::clienttype() const {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Login_REQ.ClientType)
  return _internal_clienttype();
}
inline void PKG_GG_LS_Login_REQ::set_clienttype(::uint32_t value) {
  _internal_set_clienttype(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Login_REQ.ClientType)
}
inline ::uint32_t PKG_GG_LS_Login_REQ::_internal_clienttype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clienttype_;
}
inline void PKG_GG_LS_Login_REQ::_internal_set_clienttype(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clienttype_ = value;
}

// uint32 AreaGroup = 6;
inline void PKG_GG_LS_Login_REQ::clear_areagroup() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.areagroup_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline ::uint32_t PKG_GG_LS_Login_REQ::areagroup() const {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AreaGroup)
  return _internal_areagroup();
}
inline void PKG_GG_LS_Login_REQ::set_areagroup(::uint32_t value) {
  _internal_set_areagroup(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Login_REQ.AreaGroup)
}
inline ::uint32_t PKG_GG_LS_Login_REQ::_internal_areagroup() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.areagroup_;
}
inline void PKG_GG_LS_Login_REQ::_internal_set_areagroup(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.areagroup_ = value;
}

// uint32 Ip = 7;
inline void PKG_GG_LS_Login_REQ::clear_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline ::uint32_t PKG_GG_LS_Login_REQ::ip() const {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Login_REQ.Ip)
  return _internal_ip();
}
inline void PKG_GG_LS_Login_REQ::set_ip(::uint32_t value) {
  _internal_set_ip(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Login_REQ.Ip)
}
inline ::uint32_t PKG_GG_LS_Login_REQ::_internal_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_;
}
inline void PKG_GG_LS_Login_REQ::_internal_set_ip(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_ = value;
}

// string InviteCode = 8;
inline void PKG_GG_LS_Login_REQ::clear_invitecode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.invitecode_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& PKG_GG_LS_Login_REQ::invitecode() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Login_REQ.InviteCode)
  return _internal_invitecode();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PKG_GG_LS_Login_REQ::set_invitecode(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.invitecode_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Login_REQ.InviteCode)
}
inline ::std::string* PROTOBUF_NONNULL PKG_GG_LS_Login_REQ::mutable_invitecode()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_invitecode();
  // @@protoc_insertion_point(field_mutable:GG_LS_Cmd.PKG_GG_LS_Login_REQ.InviteCode)
  return _s;
}
inline const ::std::string& PKG_GG_LS_Login_REQ::_internal_invitecode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.invitecode_.Get();
}
inline void PKG_GG_LS_Login_REQ::_internal_set_invitecode(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.invitecode_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PKG_GG_LS_Login_REQ::_internal_mutable_invitecode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.invitecode_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PKG_GG_LS_Login_REQ::release_invitecode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GG_LS_Cmd.PKG_GG_LS_Login_REQ.InviteCode)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.invitecode_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.invitecode_.Set("", GetArena());
  }
  return released;
}
inline void PKG_GG_LS_Login_REQ::set_allocated_invitecode(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.invitecode_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.invitecode_.IsDefault()) {
    _impl_.invitecode_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GG_LS_Cmd.PKG_GG_LS_Login_REQ.InviteCode)
}

// uint32 Reserve = 9;
inline void PKG_GG_LS_Login_REQ::clear_reserve() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reserve_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
}
inline ::uint32_t PKG_GG_LS_Login_REQ::reserve() const {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Login_REQ.Reserve)
  return _internal_reserve();
}
inline void PKG_GG_LS_Login_REQ::set_reserve(::uint32_t value) {
  _internal_set_reserve(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Login_REQ.Reserve)
}
inline ::uint32_t PKG_GG_LS_Login_REQ::_internal_reserve() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reserve_;
}
inline void PKG_GG_LS_Login_REQ::_internal_set_reserve(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reserve_ = value;
}

// -------------------------------------------------------------------

// PKG_LS_GG_Login_ACK

// uint32 Result = 1;
inline void PKG_LS_GG_Login_ACK::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::uint32_t PKG_LS_GG_Login_ACK::result() const {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_LS_GG_Login_ACK.Result)
  return _internal_result();
}
inline void PKG_LS_GG_Login_ACK::set_result(::uint32_t value) {
  _internal_set_result(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_LS_GG_Login_ACK.Result)
}
inline ::uint32_t PKG_LS_GG_Login_ACK::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_;
}
inline void PKG_LS_GG_Login_ACK::_internal_set_result(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = value;
}

// string PTID = 2;
inline void PKG_LS_GG_Login_ACK::clear_ptid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ptid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& PKG_LS_GG_Login_ACK::ptid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_LS_GG_Login_ACK.PTID)
  return _internal_ptid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PKG_LS_GG_Login_ACK::set_ptid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.ptid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_LS_GG_Login_ACK.PTID)
}
inline ::std::string* PROTOBUF_NONNULL PKG_LS_GG_Login_ACK::mutable_ptid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_ptid();
  // @@protoc_insertion_point(field_mutable:GG_LS_Cmd.PKG_LS_GG_Login_ACK.PTID)
  return _s;
}
inline const ::std::string& PKG_LS_GG_Login_ACK::_internal_ptid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ptid_.Get();
}
inline void PKG_LS_GG_Login_ACK::_internal_set_ptid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ptid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PKG_LS_GG_Login_ACK::_internal_mutable_ptid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ptid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PKG_LS_GG_Login_ACK::release_ptid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GG_LS_Cmd.PKG_LS_GG_Login_ACK.PTID)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.ptid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ptid_.Set("", GetArena());
  }
  return released;
}
inline void PKG_LS_GG_Login_ACK::set_allocated_ptid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.ptid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ptid_.IsDefault()) {
    _impl_.ptid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GG_LS_Cmd.PKG_LS_GG_Login_ACK.PTID)
}

// uint32 wPlatType = 3;
inline void PKG_LS_GG_Login_ACK::clear_wplattype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.wplattype_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::uint32_t PKG_LS_GG_Login_ACK::wplattype() const {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_LS_GG_Login_ACK.wPlatType)
  return _internal_wplattype();
}
inline void PKG_LS_GG_Login_ACK::set_wplattype(::uint32_t value) {
  _internal_set_wplattype(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_LS_GG_Login_ACK.wPlatType)
}
inline ::uint32_t PKG_LS_GG_Login_ACK::_internal_wplattype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.wplattype_;
}
inline void PKG_LS_GG_Login_ACK::_internal_set_wplattype(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.wplattype_ = value;
}

// string abyDataInfo = 4;
inline void PKG_LS_GG_Login_ACK::clear_abydatainfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.abydatainfo_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& PKG_LS_GG_Login_ACK::abydatainfo() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_LS_GG_Login_ACK.abyDataInfo)
  return _internal_abydatainfo();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PKG_LS_GG_Login_ACK::set_abydatainfo(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.abydatainfo_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_LS_GG_Login_ACK.abyDataInfo)
}
inline ::std::string* PROTOBUF_NONNULL PKG_LS_GG_Login_ACK::mutable_abydatainfo()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_abydatainfo();
  // @@protoc_insertion_point(field_mutable:GG_LS_Cmd.PKG_LS_GG_Login_ACK.abyDataInfo)
  return _s;
}
inline const ::std::string& PKG_LS_GG_Login_ACK::_internal_abydatainfo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.abydatainfo_.Get();
}
inline void PKG_LS_GG_Login_ACK::_internal_set_abydatainfo(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.abydatainfo_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PKG_LS_GG_Login_ACK::_internal_mutable_abydatainfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.abydatainfo_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PKG_LS_GG_Login_ACK::release_abydatainfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GG_LS_Cmd.PKG_LS_GG_Login_ACK.abyDataInfo)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.abydatainfo_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.abydatainfo_.Set("", GetArena());
  }
  return released;
}
inline void PKG_LS_GG_Login_ACK::set_allocated_abydatainfo(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.abydatainfo_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.abydatainfo_.IsDefault()) {
    _impl_.abydatainfo_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GG_LS_Cmd.PKG_LS_GG_Login_ACK.abyDataInfo)
}

// uint32 error = 5;
inline void PKG_LS_GG_Login_ACK::clear_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::uint32_t PKG_LS_GG_Login_ACK::error() const {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_LS_GG_Login_ACK.error)
  return _internal_error();
}
inline void PKG_LS_GG_Login_ACK::set_error(::uint32_t value) {
  _internal_set_error(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_LS_GG_Login_ACK.error)
}
inline ::uint32_t PKG_LS_GG_Login_ACK::_internal_error() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_;
}
inline void PKG_LS_GG_Login_ACK::_internal_set_error(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = value;
}

// -------------------------------------------------------------------

// PKG_GG_LS_Logoff_NTF

// string PTID = 1;
inline void PKG_GG_LS_Logoff_NTF::clear_ptid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ptid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& PKG_GG_LS_Logoff_NTF::ptid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF.PTID)
  return _internal_ptid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PKG_GG_LS_Logoff_NTF::set_ptid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.ptid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF.PTID)
}
inline ::std::string* PROTOBUF_NONNULL PKG_GG_LS_Logoff_NTF::mutable_ptid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_ptid();
  // @@protoc_insertion_point(field_mutable:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF.PTID)
  return _s;
}
inline const ::std::string& PKG_GG_LS_Logoff_NTF::_internal_ptid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ptid_.Get();
}
inline void PKG_GG_LS_Logoff_NTF::_internal_set_ptid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ptid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PKG_GG_LS_Logoff_NTF::_internal_mutable_ptid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ptid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PKG_GG_LS_Logoff_NTF::release_ptid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF.PTID)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.ptid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ptid_.Set("", GetArena());
  }
  return released;
}
inline void PKG_GG_LS_Logoff_NTF::set_allocated_ptid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.ptid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ptid_.IsDefault()) {
    _impl_.ptid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF.PTID)
}

// -------------------------------------------------------------------

// PKG_LS_GG_Kickoff_NTF

// string PTID = 1;
inline void PKG_LS_GG_Kickoff_NTF::clear_ptid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ptid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& PKG_LS_GG_Kickoff_NTF::ptid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF.PTID)
  return _internal_ptid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PKG_LS_GG_Kickoff_NTF::set_ptid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.ptid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF.PTID)
}
inline ::std::string* PROTOBUF_NONNULL PKG_LS_GG_Kickoff_NTF::mutable_ptid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_ptid();
  // @@protoc_insertion_point(field_mutable:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF.PTID)
  return _s;
}
inline const ::std::string& PKG_LS_GG_Kickoff_NTF::_internal_ptid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ptid_.Get();
}
inline void PKG_LS_GG_Kickoff_NTF::_internal_set_ptid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ptid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PKG_LS_GG_Kickoff_NTF::_internal_mutable_ptid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ptid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PKG_LS_GG_Kickoff_NTF::release_ptid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF.PTID)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.ptid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ptid_.Set("", GetArena());
  }
  return released;
}
inline void PKG_LS_GG_Kickoff_NTF::set_allocated_ptid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.ptid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ptid_.IsDefault()) {
    _impl_.ptid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF.PTID)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace GG_LS_Cmd


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // gg_5fls_2eproto_2epb_2eh
