// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gg_ls.proto
// Protobuf C++ Version: 7.36.1

#include "gg_ls.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GG_LS_Cmd {
class PKG_LS_GG_Login_ACK::_Internal {
 public:
  using HasBits = decltype(::std::declval<PKG_LS_GG_Login_ACK>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_._has_bits_);
};

constexpr PKG_LS_GG_Login_ACK::ParseTableT_ PKG_LS_GG_Login_ACK::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_._has_bits_),
      0, // no _extensions_
      5, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967264,  // skipmap
      offsetof(ParseTableT_, field_entries),
      5,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::GG_LS_Cmd::PKG_LS_GG_Login_ACK>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // uint32 Result = 1;
      {::_pbi::TcParser::FastV32S1,
       {8, 2, 0,
        PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.result_)}},
      // string PTID = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.ptid_)}},
      // uint32 wPlatType = 3;
      {::_pbi::TcParser::FastV32S1,
       {24, 3, 0,
        PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.wplattype_)}},
      // string abyDataInfo = 4;
      {::_pbi::TcParser::FastUS1,
       {34, 1, 0,
        PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.abydatainfo_)}},
      // uint32 error = 5;
      {::_pbi::TcParser::FastV32S1,
       {40, 4, 0,
        PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.error_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // uint32 Result = 1;
      {PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.result_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // string PTID = 2;
      {PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.ptid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // uint32 wPlatType = 3;
      {PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.wplattype_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // string abyDataInfo = 4;
      {PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.abydatainfo_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // uint32 error = 5;
      {PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.error_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
      "\35\0\4\0\13\0\0\0"
      "GG_LS_Cmd.PKG_LS_GG_Login_ACK"
      "PTID"
      "abyDataInfo"
    }},
  };
}


inline constexpr PKG_LS_GG_Login_ACK::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : ptid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        abydatainfo_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        result_{0u},
        wplattype_{0u},
        error_{0u} {}

template <typename>
constexpr PKG_LS_GG_Login_ACK::PKG_LS_GG_Login_ACK(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PKG_LS_GG_Login_ACK::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PKG_LS_GG_Login_ACK(arena);
}
constexpr auto PKG_LS_GG_Login_ACK::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PKG_LS_GG_Login_ACK), alignof(PKG_LS_GG_Login_ACK));
}
constexpr auto PKG_LS_GG_Login_ACK::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PKG_LS_GG_Login_ACK::MergeImpl,
          Super_::GetNewImpl<PKG_LS_GG_Login_ACK>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PKG_LS_GG_Login_ACK::SharedDtor,
          Super_::GetClearImpl<PKG_LS_GG_Login_ACK>(), &PKG_LS_GG_Login_ACK::ByteSizeLong,
              &PKG_LS_GG_Login_ACK::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_._cached_size_),
          true,
      },
      "GG_LS_Cmd.PKG_LS_GG_Login_ACK",
  };
}
struct PKG_LS_GG_Login_ACKGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PKG_LS_GG_Login_ACKGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PKG_LS_GG_Login_ACK_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PKG_LS_GG_Login_ACK::InternalGenerateClassData_(
            _default, &PKG_LS_GG_Login_ACK_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PKG_LS_GG_Login_ACK>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PKG_LS_GG_Login_ACKGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PKG_LS_GG_Login_ACK _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PKG_LS_GG_Login_ACK>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACKGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PKG_LS_GG_Login_ACKGlobalsTypeInternal PKG_LS_GG_Login_ACK_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PKG_LS_GG_Login_ACK_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PKG_LS_GG_Login_ACK_globals_.GetClassData();
#else
  return PKG_LS_GG_Login_ACK_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class PKG_LS_GG_Kickoff_NTF::_Internal {
 public:
  using HasBits = decltype(::std::declval<PKG_LS_GG_Kickoff_NTF>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Kickoff_NTF, _impl_._has_bits_);
};

constexpr PKG_LS_GG_Kickoff_NTF::ParseTableT_ PKG_LS_GG_Kickoff_NTF::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Kickoff_NTF, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::GG_LS_Cmd::PKG_LS_GG_Kickoff_NTF>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string PTID = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Kickoff_NTF, _impl_.ptid_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string PTID = 1;
      {PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Kickoff_NTF, _impl_.ptid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\37\4\0\0\0\0\0\0"
      "GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF"
      "PTID"
    }},
  };
}


inline constexpr PKG_LS_GG_Kickoff_NTF::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : ptid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr PKG_LS_GG_Kickoff_NTF::PKG_LS_GG_Kickoff_NTF(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PKG_LS_GG_Kickoff_NTF::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PKG_LS_GG_Kickoff_NTF(arena);
}
constexpr auto PKG_LS_GG_Kickoff_NTF::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PKG_LS_GG_Kickoff_NTF), alignof(PKG_LS_GG_Kickoff_NTF));
}
constexpr auto PKG_LS_GG_Kickoff_NTF::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PKG_LS_GG_Kickoff_NTF::MergeImpl,
          Super_::GetNewImpl<PKG_LS_GG_Kickoff_NTF>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PKG_LS_GG_Kickoff_NTF::SharedDtor,
          Super_::GetClearImpl<PKG_LS_GG_Kickoff_NTF>(), &PKG_LS_GG_Kickoff_NTF::ByteSizeLong,
              &PKG_LS_GG_Kickoff_NTF::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Kickoff_NTF, _impl_._cached_size_),
          true,
      },
      "GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF",
  };
}
struct PKG_LS_GG_Kickoff_NTFGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PKG_LS_GG_Kickoff_NTFGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PKG_LS_GG_Kickoff_NTF_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PKG_LS_GG_Kickoff_NTF::InternalGenerateClassData_(
            _default, &PKG_LS_GG_Kickoff_NTF_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PKG_LS_GG_Kickoff_NTF>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PKG_LS_GG_Kickoff_NTFGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PKG_LS_GG_Kickoff_NTF _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PKG_LS_GG_Kickoff_NTF>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Kickoff_NTFGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PKG_LS_GG_Kickoff_NTFGlobalsTypeInternal PKG_LS_GG_Kickoff_NTF_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PKG_LS_GG_Kickoff_NTF_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PKG_LS_GG_Kickoff_NTF_globals_.GetClassData();
#else
  return PKG_LS_GG_Kickoff_NTF_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class PKG_GG_LS_Logoff_NTF::_Internal {
 public:
  using HasBits = decltype(::std::declval<PKG_GG_LS_Logoff_NTF>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Logoff_NTF, _impl_._has_bits_);
};

constexpr PKG_GG_LS_Logoff_NTF::ParseTableT_ PKG_GG_LS_Logoff_NTF::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Logoff_NTF, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::GG_LS_Cmd::PKG_GG_LS_Logoff_NTF>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string PTID = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Logoff_NTF, _impl_.ptid_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string PTID = 1;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Logoff_NTF, _impl_.ptid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\36\4\0\0\0\0\0\0"
      "GG_LS_Cmd.PKG_GG_LS_Logoff_NTF"
      "PTID"
    }},
  };
}


inline constexpr PKG_GG_LS_Logoff_NTF::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : ptid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr PKG_GG_LS_Logoff_NTF::PKG_GG_LS_Logoff_NTF(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PKG_GG_LS_Logoff_NTF::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PKG_GG_LS_Logoff_NTF(arena);
}
constexpr auto PKG_GG_LS_Logoff_NTF::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PKG_GG_LS_Logoff_NTF), alignof(PKG_GG_LS_Logoff_NTF));
}
constexpr auto PKG_GG_LS_Logoff_NTF::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PKG_GG_LS_Logoff_NTF::MergeImpl,
          Super_::GetNewImpl<PKG_GG_LS_Logoff_NTF>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PKG_GG_LS_Logoff_NTF::SharedDtor,
          Super_::GetClearImpl<PKG_GG_LS_Logoff_NTF>(), &PKG_GG_LS_Logoff_NTF::ByteSizeLong,
              &PKG_GG_LS_Logoff_NTF::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Logoff_NTF, _impl_._cached_size_),
          true,
      },
      "GG_LS_Cmd.PKG_GG_LS_Logoff_NTF",
  };
}
struct PKG_GG_LS_Logoff_NTFGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PKG_GG_LS_Logoff_NTFGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PKG_GG_LS_Logoff_NTF_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PKG_GG_LS_Logoff_NTF::InternalGenerateClassData_(
            _default, &PKG_GG_LS_Logoff_NTF_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PKG_GG_LS_Logoff_NTF>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PKG_GG_LS_Logoff_NTFGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PKG_GG_LS_Logoff_NTF _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PKG_GG_LS_Logoff_NTF>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Logoff_NTFGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PKG_GG_LS_Logoff_NTFGlobalsTypeInternal PKG_GG_LS_Logoff_NTF_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PKG_GG_LS_Logoff_NTF_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PKG_GG_LS_Logoff_NTF_globals_.GetClassData();
#else
  return PKG_GG_LS_Logoff_NTF_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class PKG_GG_LS_Login_REQ::_Internal {
 public:
  using HasBits = decltype(::std::declval<PKG_GG_LS_Login_REQ>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_._has_bits_);
};

constexpr PKG_GG_LS_Login_REQ::ParseTableT_ PKG_GG_LS_Login_REQ::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_._has_bits_),
      0, // no _extensions_
      9, 120,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294966784,  // skipmap
      offsetof(ParseTableT_, field_entries),
      9,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::GG_LS_Cmd::PKG_GG_LS_Login_REQ>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // string AuthAct = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.authact_)}},
      // string AuthStr = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.authstr_)}},
      // uint32 APType = 3;
      {::_pbi::TcParser::FastV32S1,
       {24, 3, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.aptype_)}},
      // uint32 ClientVersion = 4;
      {::_pbi::TcParser::FastV32S1,
       {32, 4, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.clientversion_)}},
      // uint32 ClientType = 5;
      {::_pbi::TcParser::FastV32S1,
       {40, 5, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.clienttype_)}},
      // uint32 AreaGroup = 6;
      {::_pbi::TcParser::FastV32S1,
       {48, 6, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.areagroup_)}},
      // uint32 Ip = 7;
      {::_pbi::TcParser::FastV32S1,
       {56, 7, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.ip_)}},
      // string InviteCode = 8;
      {::_pbi::TcParser::FastUS1,
       {66, 2, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.invitecode_)}},
      // uint32 Reserve = 9;
      {::_pbi::TcParser::FastV32S1,
       {72, 8, 0,
        PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.reserve_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // string AuthAct = 1;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.authact_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string AuthStr = 2;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.authstr_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // uint32 APType = 3;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.aptype_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // uint32 ClientVersion = 4;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.clientversion_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // uint32 ClientType = 5;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.clienttype_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // uint32 AreaGroup = 6;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.areagroup_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // uint32 Ip = 7;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.ip_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // string InviteCode = 8;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.invitecode_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // uint32 Reserve = 9;
      {PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.reserve_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
      "\35\7\7\0\0\0\0\0\12\0\0\0\0\0\0\0"
      "GG_LS_Cmd.PKG_GG_LS_Login_REQ"
      "AuthAct"
      "AuthStr"
      "InviteCode"
    }},
  };
}


inline constexpr PKG_GG_LS_Login_REQ::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : authact_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        authstr_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        invitecode_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        aptype_{0u},
        clientversion_{0u},
        clienttype_{0u},
        areagroup_{0u},
        ip_{0u},
        reserve_{0u} {}

template <typename>
constexpr PKG_GG_LS_Login_REQ::PKG_GG_LS_Login_REQ(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PKG_GG_LS_Login_REQ::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PKG_GG_LS_Login_REQ(arena);
}
constexpr auto PKG_GG_LS_Login_REQ::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PKG_GG_LS_Login_REQ), alignof(PKG_GG_LS_Login_REQ));
}
constexpr auto PKG_GG_LS_Login_REQ::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PKG_GG_LS_Login_REQ::MergeImpl,
          Super_::GetNewImpl<PKG_GG_LS_Login_REQ>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PKG_GG_LS_Login_REQ::SharedDtor,
          Super_::GetClearImpl<PKG_GG_LS_Login_REQ>(), &PKG_GG_LS_Login_REQ::ByteSizeLong,
              &PKG_GG_LS_Login_REQ::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_._cached_size_),
          true,
      },
      "GG_LS_Cmd.PKG_GG_LS_Login_REQ",
  };
}
struct PKG_GG_LS_Login_REQGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PKG_GG_LS_Login_REQGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PKG_GG_LS_Login_REQ_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PKG_GG_LS_Login_REQ::InternalGenerateClassData_(
            _default, &PKG_GG_LS_Login_REQ_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PKG_GG_LS_Login_REQ>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PKG_GG_LS_Login_REQGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PKG_GG_LS_Login_REQ _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PKG_GG_LS_Login_REQ>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PKG_GG_LS_Login_REQGlobalsTypeInternal PKG_GG_LS_Login_REQ_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PKG_GG_LS_Login_REQ_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PKG_GG_LS_Login_REQ_globals_.GetClassData();
#else
  return PKG_GG_LS_Login_REQ_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace GG_LS_Cmd
namespace GG_LS_Cmd {
// ===================================================================

PKG_GG_LS_Login_REQ::PKG_GG_LS_Login_REQ(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, PKG_GG_LS_Login_REQ_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
}
PROTOBUF_NDEBUG_INLINE PKG_GG_LS_Login_REQ::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::GG_LS_Cmd::PKG_GG_LS_Login_REQ& from_msg)
      : _has_bits_{from._has_bits_},
        authact_(arena, from.authact_),
        authstr_(arena, from.authstr_),
        invitecode_(arena, from.invitecode_) {}

PKG_GG_LS_Login_REQ::PKG_GG_LS_Login_REQ(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PKG_GG_LS_Login_REQ& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, PKG_GG_LS_Login_REQ_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PKG_GG_LS_Login_REQ* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, aptype_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, aptype_),
           offsetof(Impl_, reserve_) -
               offsetof(Impl_, aptype_) +
               sizeof(Impl_::reserve_));

  // @@protoc_insertion_point(copy_constructor:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
}
PROTOBUF_NDEBUG_INLINE PKG_GG_LS_Login_REQ::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : authact_(arena),
        authstr_(arena),
        invitecode_(arena) {}

inline void PKG_GG_LS_Login_REQ::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, aptype_),
           0,
           offsetof(Impl_, reserve_) -
               offsetof(Impl_, aptype_) +
               sizeof(Impl_::reserve_));
}
PKG_GG_LS_Login_REQ::~PKG_GG_LS_Login_REQ() {
  // @@protoc_insertion_point(destructor:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
  SharedDtor(*this);
}
inline void PKG_GG_LS_Login_REQ::SharedDtor(MessageLite& self) {
  PKG_GG_LS_Login_REQ& this_ = static_cast<PKG_GG_LS_Login_REQ&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.authact_.Destroy();
  this_._impl_.authstr_.Destroy();
  this_._impl_.invitecode_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite PKG_GG_LS_Login_REQ_class_data_ =
    PKG_GG_LS_Login_REQ::InternalGenerateClassData_(PKG_GG_LS_Login_REQ_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PKG_GG_LS_Login_REQ::GetClassData() const {
  return PKG_GG_LS_Login_REQ_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PKG_GG_LS_Login_REQ::GetClassData() const {
  return PKG_GG_LS_Login_REQ_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PKG_GG_LS_Login_REQ::ParseTableT_
    PKG_GG_LS_Login_REQ::_table_ =
        PKG_GG_LS_Login_REQ::InternalGenerateParseTable_(PKG_GG_LS_Login_REQ_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PKG_GG_LS_Login_REQ::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      this_._impl_.authact_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      this_._impl_.authstr_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      this_._impl_.invitecode_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f8U)) {
    ::memset(&this_._impl_.aptype_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.ip_) -
                 reinterpret_cast<char*>(&this_._impl_.aptype_)) +
                 sizeof(_impl_.ip_));
  }
  this_._impl_.reserve_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PKG_GG_LS_Login_REQ::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PKG_GG_LS_Login_REQ& this_ = static_cast<const PKG_GG_LS_Login_REQ&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PKG_GG_LS_Login_REQ::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PKG_GG_LS_Login_REQ& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string AuthAct = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_authact().empty()) {
      const ::std::string& _s = this_._internal_authact();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthAct");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string AuthStr = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_authstr().empty()) {
      const ::std::string& _s = this_._internal_authstr();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GG_LS_Cmd.PKG_GG_LS_Login_REQ.AuthStr");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // uint32 APType = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_aptype() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_aptype(), target);
    }
  }

  // uint32 ClientVersion = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_clientversion() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          4, this_._internal_clientversion(), target);
    }
  }

  // uint32 ClientType = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_clienttype() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_clienttype(), target);
    }
  }

  // uint32 AreaGroup = 6;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_areagroup() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          6, this_._internal_areagroup(), target);
    }
  }

  // uint32 Ip = 7;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_ip() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          7, this_._internal_ip(), target);
    }
  }

  // string InviteCode = 8;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_invitecode().empty()) {
      const ::std::string& _s = this_._internal_invitecode();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GG_LS_Cmd.PKG_GG_LS_Login_REQ.InviteCode");
      target = stream->WriteStringMaybeAliased(8, _s, target);
    }
  }

  // uint32 Reserve = 9;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_reserve() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          9, this_._internal_reserve(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PKG_GG_LS_Login_REQ::ByteSizeLong(const MessageLite& base) {
  const PKG_GG_LS_Login_REQ& this_ = static_cast<const PKG_GG_LS_Login_REQ&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PKG_GG_LS_Login_REQ::ByteSizeLong() const {
  const PKG_GG_LS_Login_REQ& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string AuthAct = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_authact().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_authact());
      }
    }
    // string AuthStr = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_authstr().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_authstr());
      }
    }
    // string InviteCode = 8;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_invitecode().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_invitecode());
      }
    }
    // uint32 APType = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_aptype() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_aptype());
      }
    }
    // uint32 ClientVersion = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_clientversion() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_clientversion());
      }
    }
    // uint32 ClientType = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_clienttype() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_clienttype());
      }
    }
    // uint32 AreaGroup = 6;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_areagroup() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_areagroup());
      }
    }
    // uint32 Ip = 7;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_ip() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_ip());
      }
    }
  }
   {
    // uint32 Reserve = 9;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_reserve() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_reserve());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void PKG_GG_LS_Login_REQ::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PKG_GG_LS_Login_REQ*>(&to_msg);
  auto& from = static_cast<const PKG_GG_LS_Login_REQ&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_authact().empty()) {
        _this->_internal_set_authact(from._internal_authact());
      } else {
        if (_this->_impl_.authact_.IsDefault()) {
          _this->_internal_set_authact("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_authstr().empty()) {
        _this->_internal_set_authstr(from._internal_authstr());
      } else {
        if (_this->_impl_.authstr_.IsDefault()) {
          _this->_internal_set_authstr("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_invitecode().empty()) {
        _this->_internal_set_invitecode(from._internal_invitecode());
      } else {
        if (_this->_impl_.invitecode_.IsDefault()) {
          _this->_internal_set_invitecode("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_aptype() != 0) {
        _this->_impl_.aptype_ = from._impl_.aptype_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_clientversion() != 0) {
        _this->_impl_.clientversion_ = from._impl_.clientversion_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_clienttype() != 0) {
        _this->_impl_.clienttype_ = from._impl_.clienttype_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_areagroup() != 0) {
        _this->_impl_.areagroup_ = from._impl_.areagroup_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_ip() != 0) {
        _this->_impl_.ip_ = from._impl_.ip_;
      }
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (from._internal_reserve() != 0) {
      _this->_impl_.reserve_ = from._impl_.reserve_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void PKG_GG_LS_Login_REQ::CopyFrom(const PKG_GG_LS_Login_REQ& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GG_LS_Cmd.PKG_GG_LS_Login_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PKG_GG_LS_Login_REQ::InternalSwap(PKG_GG_LS_Login_REQ* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.authact_, &other->_impl_.authact_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.authstr_, &other->_impl_.authstr_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.invitecode_, &other->_impl_.invitecode_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.reserve_)
      + sizeof(PKG_GG_LS_Login_REQ::_impl_.reserve_)
      - PROTOBUF_FIELD_OFFSET(PKG_GG_LS_Login_REQ, _impl_.aptype_)>(
          reinterpret_cast<char*>(&_impl_.aptype_),
          reinterpret_cast<char*>(&other->_impl_.aptype_));
}

// ===================================================================

PKG_LS_GG_Login_ACK::PKG_LS_GG_Login_ACK(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, PKG_LS_GG_Login_ACK_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
}
PROTOBUF_NDEBUG_INLINE PKG_LS_GG_Login_ACK::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::GG_LS_Cmd::PKG_LS_GG_Login_ACK& from_msg)
      : _has_bits_{from._has_bits_},
        ptid_(arena, from.ptid_),
        abydatainfo_(arena, from.abydatainfo_) {}

PKG_LS_GG_Login_ACK::PKG_LS_GG_Login_ACK(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PKG_LS_GG_Login_ACK& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, PKG_LS_GG_Login_ACK_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PKG_LS_GG_Login_ACK* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, result_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, result_),
           offsetof(Impl_, error_) -
               offsetof(Impl_, result_) +
               sizeof(Impl_::error_));

  // @@protoc_insertion_point(copy_constructor:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
}
PROTOBUF_NDEBUG_INLINE PKG_LS_GG_Login_ACK::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : ptid_(arena),
        abydatainfo_(arena) {}

inline void PKG_LS_GG_Login_ACK::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, result_),
           0,
           offsetof(Impl_, error_) -
               offsetof(Impl_, result_) +
               sizeof(Impl_::error_));
}
PKG_LS_GG_Login_ACK::~PKG_LS_GG_Login_ACK() {
  // @@protoc_insertion_point(destructor:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
  SharedDtor(*this);
}
inline void PKG_LS_GG_Login_ACK::SharedDtor(MessageLite& self) {
  PKG_LS_GG_Login_ACK& this_ = static_cast<PKG_LS_GG_Login_ACK&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ptid_.Destroy();
  this_._impl_.abydatainfo_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite PKG_LS_GG_Login_ACK_class_data_ =
    PKG_LS_GG_Login_ACK::InternalGenerateClassData_(PKG_LS_GG_Login_ACK_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PKG_LS_GG_Login_ACK::GetClassData() const {
  return PKG_LS_GG_Login_ACK_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PKG_LS_GG_Login_ACK::GetClassData() const {
  return PKG_LS_GG_Login_ACK_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PKG_LS_GG_Login_ACK::ParseTableT_
    PKG_LS_GG_Login_ACK::_table_ =
        PKG_LS_GG_Login_ACK::InternalGenerateParseTable_(PKG_LS_GG_Login_ACK_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PKG_LS_GG_Login_ACK::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      this_._impl_.ptid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      this_._impl_.abydatainfo_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001cU)) {
    ::memset(&this_._impl_.result_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.error_) -
                 reinterpret_cast<char*>(&this_._impl_.result_)) +
                 sizeof(_impl_.error_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PKG_LS_GG_Login_ACK::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PKG_LS_GG_Login_ACK& this_ = static_cast<const PKG_LS_GG_Login_ACK&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PKG_LS_GG_Login_ACK::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PKG_LS_GG_Login_ACK& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 Result = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_result() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_result(), target);
    }
  }

  // string PTID = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_ptid().empty()) {
      const ::std::string& _s = this_._internal_ptid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GG_LS_Cmd.PKG_LS_GG_Login_ACK.PTID");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // uint32 wPlatType = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_wplattype() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_wplattype(), target);
    }
  }

  // string abyDataInfo = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_abydatainfo().empty()) {
      const ::std::string& _s = this_._internal_abydatainfo();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GG_LS_Cmd.PKG_LS_GG_Login_ACK.abyDataInfo");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // uint32 error = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_error() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_error(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PKG_LS_GG_Login_ACK::ByteSizeLong(const MessageLite& base) {
  const PKG_LS_GG_Login_ACK& this_ = static_cast<const PKG_LS_GG_Login_ACK&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PKG_LS_GG_Login_ACK::ByteSizeLong() const {
  const PKG_LS_GG_Login_ACK& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string PTID = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_ptid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ptid());
      }
    }
    // string abyDataInfo = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_abydatainfo().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_abydatainfo());
      }
    }
    // uint32 Result = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_result() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_result());
      }
    }
    // uint32 wPlatType = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_wplattype() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_wplattype());
      }
    }
    // uint32 error = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_error() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_error());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void PKG_LS_GG_Login_ACK::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PKG_LS_GG_Login_ACK*>(&to_msg);
  auto& from = static_cast<const PKG_LS_GG_Login_ACK&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_ptid().empty()) {
        _this->_internal_set_ptid(from._internal_ptid());
      } else {
        if (_this->_impl_.ptid_.IsDefault()) {
          _this->_internal_set_ptid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_abydatainfo().empty()) {
        _this->_internal_set_abydatainfo(from._internal_abydatainfo());
      } else {
        if (_this->_impl_.abydatainfo_.IsDefault()) {
          _this->_internal_set_abydatainfo("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_result() != 0) {
        _this->_impl_.result_ = from._impl_.result_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_wplattype() != 0) {
        _this->_impl_.wplattype_ = from._impl_.wplattype_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_error() != 0) {
        _this->_impl_.error_ = from._impl_.error_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void PKG_LS_GG_Login_ACK::CopyFrom(const PKG_LS_GG_Login_ACK& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GG_LS_Cmd.PKG_LS_GG_Login_ACK)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PKG_LS_GG_Login_ACK::InternalSwap(PKG_LS_GG_Login_ACK* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ptid_, &other->_impl_.ptid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.abydatainfo_, &other->_impl_.abydatainfo_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.error_)
      + sizeof(PKG_LS_GG_Login_ACK::_impl_.error_)
      - PROTOBUF_FIELD_OFFSET(PKG_LS_GG_Login_ACK, _impl_.result_)>(
          reinterpret_cast<char*>(&_impl_.result_),
          reinterpret_cast<char*>(&other->_impl_.result_));
}

// ===================================================================

PKG_GG_LS_Logoff_NTF::PKG_GG_LS_Logoff_NTF(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, PKG_GG_LS_Logoff_NTF_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
}
PROTOBUF_NDEBUG_INLINE PKG_GG_LS_Logoff_NTF::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::GG_LS_Cmd::PKG_GG_LS_Logoff_NTF& from_msg)
      : _has_bits_{from._has_bits_},
        ptid_(arena, from.ptid_) {}

PKG_GG_LS_Logoff_NTF::PKG_GG_LS_Logoff_NTF(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PKG_GG_LS_Logoff_NTF& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, PKG_GG_LS_Logoff_NTF_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PKG_GG_LS_Logoff_NTF* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
}
PROTOBUF_NDEBUG_INLINE PKG_GG_LS_Logoff_NTF::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : ptid_(arena) {}

inline void PKG_GG_LS_Logoff_NTF::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PKG_GG_LS_Logoff_NTF::~PKG_GG_LS_Logoff_NTF() {
  // @@protoc_insertion_point(destructor:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
  SharedDtor(*this);
}
inline void PKG_GG_LS_Logoff_NTF::SharedDtor(MessageLite& self) {
  PKG_GG_LS_Logoff_NTF& this_ = static_cast<PKG_GG_LS_Logoff_NTF&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ptid_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite PKG_GG_LS_Logoff_NTF_class_data_ =
    PKG_GG_LS_Logoff_NTF::InternalGenerateClassData_(PKG_GG_LS_Logoff_NTF_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PKG_GG_LS_Logoff_NTF::GetClassData() const {
  return PKG_GG_LS_Logoff_NTF_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PKG_GG_LS_Logoff_NTF::GetClassData() const {
  return PKG_GG_LS_Logoff_NTF_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PKG_GG_LS_Logoff_NTF::ParseTableT_
    PKG_GG_LS_Logoff_NTF::_table_ =
        PKG_GG_LS_Logoff_NTF::InternalGenerateParseTable_(PKG_GG_LS_Logoff_NTF_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PKG_GG_LS_Logoff_NTF::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    this_._impl_.ptid_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PKG_GG_LS_Logoff_NTF::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PKG_GG_LS_Logoff_NTF& this_ = static_cast<const PKG_GG_LS_Logoff_NTF&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PKG_GG_LS_Logoff_NTF::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PKG_GG_LS_Logoff_NTF& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string PTID = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_ptid().empty()) {
      const ::std::string& _s = this_._internal_ptid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GG_LS_Cmd.PKG_GG_LS_Logoff_NTF.PTID");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PKG_GG_LS_Logoff_NTF::ByteSizeLong(const MessageLite& base) {
  const PKG_GG_LS_Logoff_NTF& this_ = static_cast<const PKG_GG_LS_Logoff_NTF&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PKG_GG_LS_Logoff_NTF::ByteSizeLong() const {
  const PKG_GG_LS_Logoff_NTF& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

   {
    // string PTID = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_ptid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ptid());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void PKG_GG_LS_Logoff_NTF::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PKG_GG_LS_Logoff_NTF*>(&to_msg);
  auto& from = static_cast<const PKG_GG_LS_Logoff_NTF&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_ptid().empty()) {
      _this->_internal_set_ptid(from._internal_ptid());
    } else {
      if (_this->_impl_.ptid_.IsDefault()) {
        _this->_internal_set_ptid("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void PKG_GG_LS_Logoff_NTF::CopyFrom(const PKG_GG_LS_Logoff_NTF& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GG_LS_Cmd.PKG_GG_LS_Logoff_NTF)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PKG_GG_LS_Logoff_NTF::InternalSwap(PKG_GG_LS_Logoff_NTF* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ptid_, &other->_impl_.ptid_, arena);
}

// ===================================================================

PKG_LS_GG_Kickoff_NTF::PKG_LS_GG_Kickoff_NTF(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, PKG_LS_GG_Kickoff_NTF_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
}
PROTOBUF_NDEBUG_INLINE PKG_LS_GG_Kickoff_NTF::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::GG_LS_Cmd::PKG_LS_GG_Kickoff_NTF& from_msg)
      : _has_bits_{from._has_bits_},
        ptid_(arena, from.ptid_) {}

PKG_LS_GG_Kickoff_NTF::PKG_LS_GG_Kickoff_NTF(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PKG_LS_GG_Kickoff_NTF& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, PKG_LS_GG_Kickoff_NTF_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PKG_LS_GG_Kickoff_NTF* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
}
PROTOBUF_NDEBUG_INLINE PKG_LS_GG_Kickoff_NTF::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : ptid_(arena) {}

inline void PKG_LS_GG_Kickoff_NTF::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PKG_LS_GG_Kickoff_NTF::~PKG_LS_GG_Kickoff_NTF() {
  // @@protoc_insertion_point(destructor:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
  SharedDtor(*this);
}
inline void PKG_LS_GG_Kickoff_NTF::SharedDtor(MessageLite& self) {
  PKG_LS_GG_Kickoff_NTF& this_ = static_cast<PKG_LS_GG_Kickoff_NTF&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ptid_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite PKG_LS_GG_Kickoff_NTF_class_data_ =
    PKG_LS_GG_Kickoff_NTF::InternalGenerateClassData_(PKG_LS_GG_Kickoff_NTF_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PKG_LS_GG_Kickoff_NTF::GetClassData() const {
  return PKG_LS_GG_Kickoff_NTF_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PKG_LS_GG_Kickoff_NTF::GetClassData() const {
  return PKG_LS_GG_Kickoff_NTF_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PKG_LS_GG_Kickoff_NTF::ParseTableT_
    PKG_LS_GG_Kickoff_NTF::_table_ =
        PKG_LS_GG_Kickoff_NTF::InternalGenerateParseTable_(PKG_LS_GG_Kickoff_NTF_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PKG_LS_GG_Kickoff_NTF::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    this_._impl_.ptid_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PKG_LS_GG_Kickoff_NTF::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PKG_LS_GG_Kickoff_NTF& this_ = static_cast<const PKG_LS_GG_Kickoff_NTF&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PKG_LS_GG_Kickoff_NTF::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PKG_LS_GG_Kickoff_NTF& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string PTID = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_ptid().empty()) {
      const ::std::string& _s = this_._internal_ptid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF.PTID");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PKG_LS_GG_Kickoff_NTF::ByteSizeLong(const MessageLite& base) {
  const PKG_LS_GG_Kickoff_NTF& this_ = static_cast<const PKG_LS_GG_Kickoff_NTF&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PKG_LS_GG_Kickoff_NTF::ByteSizeLong() const {
  const PKG_LS_GG_Kickoff_NTF& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

   {
    // string PTID = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_ptid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ptid());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void PKG_LS_GG_Kickoff_NTF::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PKG_LS_GG_Kickoff_NTF*>(&to_msg);
  auto& from = static_cast<const PKG_LS_GG_Kickoff_NTF&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_ptid().empty()) {
      _this->_internal_set_ptid(from._internal_ptid());
    } else {
      if (_this->_impl_.ptid_.IsDefault()) {
        _this->_internal_set_ptid("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void PKG_LS_GG_Kickoff_NTF::CopyFrom(const PKG_LS_GG_Kickoff_NTF& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GG_LS_Cmd.PKG_LS_GG_Kickoff_NTF)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PKG_LS_GG_Kickoff_NTF::InternalSwap(PKG_LS_GG_Kickoff_NTF* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ptid_, &other->_impl_.ptid_, arena);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace GG_LS_Cmd
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
