[Client]
MaxClientNum=2000

[GameGate]
ListenPort=8700
ListenIP=127.0.0.1
GroupName=0
GatePipeID=250-2-4-0

AdapterSrvIP=192.168.6.18
AdapterSrvPort=8800

Latest=0
LatestArea=0

[GameServer]
GsNum=1

GS_0_IP=127.0.0.1
GS_0_Port=8600
GS_0_No=0

GS_1_IP=127.0.0.1
GS_1_Port=8601
GS_1_No=1


[Debug]
#1为true，0为false
IsNeedDynamicCode=0
IsCliNeedStaticCode=0

CreateRoleOnlyMsg=本服务器目前尚未开放游戏功能。敬请耐心等待，新区期待您的光临！
IsCreateRoleOnly=0

#心跳次数
timeoutHitCnts=200

[AttributeCheck]
SlayerMinAttributeValue=5
SlayerMaxAttributeValue=20
SlayerTotalAttributeValue=30
VampireMinAttributeValue=20
VampireMaxAttributeValue=20
VampireTotalAttributeValue=60
OustersMinAttributeValue=10
OustersMaxAttributeValue=25
OustersTotalAttributeValue=45

