[Server]
#MySql
User=root
PassWord=123456
MysqlPort=3306
MysqlIP='127.0.0.1'

MysqlDBLog='tl_log'
MysqlLogic='tl_game'


UseCloud=0
LogUser='root'
LogPassWord='b3lmdWllMkAyMDMwOQ=='
LogMysqlPort=3306
LogMysqlIP='10.66.227.69'

#是否是测试服
IsTest=true

#区信息
Area=250
AreaName='测试区'

#组信息
Group=2
GroupName='内网'

#GS信息
ServerIndex=0
ServerPort=8600

#组内GS数量
ServerCount=1

#分区列表url
ZoneListUrl='http://192.168.6.76:7200/api/v1/server/getServerInfo'

[Share]
EnvirDir='.\gamedata\'
MapDir='.\gamedata\map\'
NoMonsterMode=true

######################################################
#数据库相关配置
[MySQL]
MysqlNum=1

Mysql_1_IP='127.0.0.1'
Mysql_1_Port=3306
Mysql_1_DBName='tl_game'
Mysql_1_UserName='root'
Mysql_1_Password='123456'
Mysql_1_Charset='utf8'
#用于SDDB的MySQL连接ID号
Mysql_1_DBSN=1

# 私域配置
[PrivateDomain]
AppId=1011
AppSecret='urN5ngWcN73vzJXqXUVhqpJuQz3zWklS'
GetRoleCodeUrl='https://swapis-server.gateway.yofijoy.com/gameapi-server/api/webhook'

# 七日累充
[AccumRecharge]
AccumRechargeTime='2025-11-06 00:00:00'