syntax = "proto3";
package GG_LS_Cmd;
option optimize_for = LITE_RUNTIME;

import "commdef.proto";

message PKG_GG_LS_Login_REQ
{
	string AuthAct = 1;
	string AuthStr = 2;
	uint32 APType = 3;
	uint32 ClientVersion = 4;
	uint32 ClientType = 5;
	uint32 AreaGroup = 6;
	uint32 Ip = 7;
	string InviteCode = 8;
	uint32 Reserve = 9;
}


message PKG_LS_GG_Login_ACK
{
	uint32 Result = 1;
	string PTID = 2;
	uint32 wPlatType = 3;// loginInfo
	string abyDataInfo = 4;// loginData
	uint32 error = 5;
}
		
message PKG_GG_LS_Logoff_NTF
{
	string PTID = 1;
}

message PKG_LS_GG_Kickoff_NTF
{
	string PTID = 1;
}
